# Generated by Django 4.2 on 2023-04-23 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_name_case_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
